### ISSUE TITLE
make db readable

### ISSUE THREAD

**Issue by ens4dz** [ens4dz/Algeria-Prayer-Times-ESP32#1]
esp32 can't handle prayer times in a  big file
need to shrink and rewrite

**Comment by amrouchk** [comment]
How much is the allowed size for esp32 to handle such files?

**Comment by ens4dz** [comment]
Total Rom is 4MBytes,
with 1Mb for the code or more
3Mb is the limit.

**Comment by ens4dz** [comment]
solved.
1- all rows before 2019 has been removed.
2- change type of  prayer time from 8 bytes string to 2 bytes int minutes, 00:00 is 0.  exp:
(02:05:00 --> 125)
3- change type of  date from 10 bytes string to 3 bytes int (2020-07-14 --> 20200712)

**Comment by amrouchk** [comment]
Great
